// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/JauntyInc/gogeocodes/client/address"
	"github.com/JauntyInc/gogeocodes/client/auth"
	"github.com/JauntyInc/gogeocodes/client/operations"
	"github.com/JauntyInc/gogeocodes/client/zip_code"
)

// Default gogeocodes HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "api.geo.codes"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"https"}

// NewHTTPClient creates a new gogeocodes HTTP client.
func NewHTTPClient(formats strfmt.Registry) *Gogeocodes {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new gogeocodes HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *Gogeocodes {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new gogeocodes client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Gogeocodes {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(Gogeocodes)
	cli.Transport = transport
	cli.Address = address.New(transport, formats)
	cli.Auth = auth.New(transport, formats)
	cli.Operations = operations.New(transport, formats)
	cli.ZIPCode = zip_code.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// Gogeocodes is a client for gogeocodes
type Gogeocodes struct {
	Address address.ClientService

	Auth auth.ClientService

	Operations operations.ClientService

	ZIPCode zip_code.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *Gogeocodes) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.Address.SetTransport(transport)
	c.Auth.SetTransport(transport)
	c.Operations.SetTransport(transport)
	c.ZIPCode.SetTransport(transport)
}
