// Code generated by go-swagger; DO NOT EDIT.

package zip_code

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/JauntyInc/gogeocodes/models"
)

// V1AddressReverseZIPCodeReader is a Reader for the V1AddressReverseZIPCode structure.
type V1AddressReverseZIPCodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1AddressReverseZIPCodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1AddressReverseZIPCodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1AddressReverseZIPCodeOK creates a V1AddressReverseZIPCodeOK with default headers values
func NewV1AddressReverseZIPCodeOK() *V1AddressReverseZIPCodeOK {
	return &V1AddressReverseZIPCodeOK{}
}

/* V1AddressReverseZIPCodeOK describes a response with status code 200, with default header values.

OK
*/
type V1AddressReverseZIPCodeOK struct {
	Payload *models.ReverseZIPCode
}

func (o *V1AddressReverseZIPCodeOK) Error() string {
	return fmt.Sprintf("[GET /v1/address/reverse_zip_code][%d] v1AddressReverseZipCodeOK  %+v", 200, o.Payload)
}
func (o *V1AddressReverseZIPCodeOK) GetPayload() *models.ReverseZIPCode {
	return o.Payload
}

func (o *V1AddressReverseZIPCodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ReverseZIPCode)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
