// Code generated by go-swagger; DO NOT EDIT.

package zip_code

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1AddressZIPCodeParams creates a new V1AddressZIPCodeParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1AddressZIPCodeParams() *V1AddressZIPCodeParams {
	return &V1AddressZIPCodeParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1AddressZIPCodeParamsWithTimeout creates a new V1AddressZIPCodeParams object
// with the ability to set a timeout on a request.
func NewV1AddressZIPCodeParamsWithTimeout(timeout time.Duration) *V1AddressZIPCodeParams {
	return &V1AddressZIPCodeParams{
		timeout: timeout,
	}
}

// NewV1AddressZIPCodeParamsWithContext creates a new V1AddressZIPCodeParams object
// with the ability to set a context for a request.
func NewV1AddressZIPCodeParamsWithContext(ctx context.Context) *V1AddressZIPCodeParams {
	return &V1AddressZIPCodeParams{
		Context: ctx,
	}
}

// NewV1AddressZIPCodeParamsWithHTTPClient creates a new V1AddressZIPCodeParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1AddressZIPCodeParamsWithHTTPClient(client *http.Client) *V1AddressZIPCodeParams {
	return &V1AddressZIPCodeParams{
		HTTPClient: client,
	}
}

/* V1AddressZIPCodeParams contains all the parameters to send to the API endpoint
   for the v1 address zip code operation.

   Typically these are written to a http.Request.
*/
type V1AddressZIPCodeParams struct {

	/* ZIPCode.

	   The ZIP Code of the query. Can be a ZIP Code or a ZIP+4 Code. If a +4 extension is passed, it will be ignored.
	*/
	ZIPCode string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1 address zip code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1AddressZIPCodeParams) WithDefaults() *V1AddressZIPCodeParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1 address zip code params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1AddressZIPCodeParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1 address zip code params
func (o *V1AddressZIPCodeParams) WithTimeout(timeout time.Duration) *V1AddressZIPCodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1 address zip code params
func (o *V1AddressZIPCodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1 address zip code params
func (o *V1AddressZIPCodeParams) WithContext(ctx context.Context) *V1AddressZIPCodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1 address zip code params
func (o *V1AddressZIPCodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1 address zip code params
func (o *V1AddressZIPCodeParams) WithHTTPClient(client *http.Client) *V1AddressZIPCodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1 address zip code params
func (o *V1AddressZIPCodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithZIPCode adds the zIPCode to the v1 address zip code params
func (o *V1AddressZIPCodeParams) WithZIPCode(zIPCode string) *V1AddressZIPCodeParams {
	o.SetZIPCode(zIPCode)
	return o
}

// SetZIPCode adds the zipCode to the v1 address zip code params
func (o *V1AddressZIPCodeParams) SetZIPCode(zIPCode string) {
	o.ZIPCode = zIPCode
}

// WriteToRequest writes these params to a swagger request
func (o *V1AddressZIPCodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param zip_code
	qrZIPCode := o.ZIPCode
	qZIPCode := qrZIPCode
	if qZIPCode != "" {

		if err := r.SetQueryParam("zip_code", qZIPCode); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
