// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// V1TestReader is a Reader for the V1Test structure.
type V1TestReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1TestReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1TestOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1TestOK creates a V1TestOK with default headers values
func NewV1TestOK() *V1TestOK {
	return &V1TestOK{}
}

/* V1TestOK describes a response with status code 200, with default header values.

authorized!
*/
type V1TestOK struct {
	Payload string
}

func (o *V1TestOK) Error() string {
	return fmt.Sprintf("[GET /v1/test][%d] v1TestOK  %+v", 200, o.Payload)
}
func (o *V1TestOK) GetPayload() string {
	return o.Payload
}

func (o *V1TestOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
