// Code generated by go-swagger; DO NOT EDIT.

package address

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/JauntyInc/gogeocodes/models"
)

// V1AddressStructuredGeocodeReader is a Reader for the V1AddressStructuredGeocode structure.
type V1AddressStructuredGeocodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1AddressStructuredGeocodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1AddressStructuredGeocodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewV1AddressStructuredGeocodeOK creates a V1AddressStructuredGeocodeOK with default headers values
func NewV1AddressStructuredGeocodeOK() *V1AddressStructuredGeocodeOK {
	return &V1AddressStructuredGeocodeOK{}
}

/* V1AddressStructuredGeocodeOK describes a response with status code 200, with default header values.

OK
*/
type V1AddressStructuredGeocodeOK struct {
	Payload *models.Geocoding
}

func (o *V1AddressStructuredGeocodeOK) Error() string {
	return fmt.Sprintf("[GET /v1/address/structured_geocode][%d] v1AddressStructuredGeocodeOK  %+v", 200, o.Payload)
}
func (o *V1AddressStructuredGeocodeOK) GetPayload() *models.Geocoding {
	return o.Payload
}

func (o *V1AddressStructuredGeocodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Geocoding)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
